spring:
  application:
    name: SCW-USER
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.110:3306/ugorfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.0.110
    port: 6379
    #password: 123456
    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true
    
server:
  port: 7000